### ISSUE TITLE
Неплохо бы было проверять, что мы не уходим в минус

### ISSUE THREAD

**Issue by coursar** [twister1803/WebApp#7]
https://github.com/twister1803/WebApp/blob/0b17d4140262bb88551208c05d62aae5dffe8c9f/src/main/java/org/example/app/repository/CardRepository.java#L20-L42

**Comment by ChekalinMikhail** [comment]
Проверка есть у метода transaction в CardService. Заодно добавил в проверку генерацию отдельных исключений для некорректной суммы перевода и недостаточном количестве средств на карте.
