### ISSUE TITLE
Сколько в параллели можно инициировать восстановлений пароля для одного пользователя?

### ISSUE THREAD

**Issue by coursar** [twister1803/WebApp#9]
https://github.com/twister1803/WebApp/blob/0b17d4140262bb88551208c05d62aae5dffe8c9f/src/main/java/org/example/app/repository/UserRepository.java#L193-L198

**Comment by ChekalinMikhail** [comment]
У одного пользователя в базе может быть только один ключ для восстановления пароля. При повторном запросе ключа старый не использованный будет удаляться в методе createKeyForPasswordRecovery UserRepository.
